version: '3.8'

services:

  service1:
    build: ./patient_service
    ports:
      - "8001:8001"

  service3:
    build: ./appointment_service
    ports:
      - "8003:8003"

  service2:
    build: ./doctor_service
    ports:
      - "8002:8002"

  service4:
    build: ./notification_service
    ports:
      - "8004:8004"

  service0:
    build: ./clinic_frontend
    ports:
      - "8000:8000"
